### ISSUE TITLE
Documentation Tracking List

### ISSUE THREAD

**Issue by TomShawn** [apache/cloudberry-site#16]
Hello Contributors,

This issue is dedicated to tracking the progress of Cloudberry Database documentation. The goal is to provide a comprehensive and up-to-date documentation for all users, and we appreciate any contributions towards achieving this aim.

The issue will follow the format of a checklist, with each item representing a specific piece of documentation that needs to be added. The item will be checked off once the corresponding Pull Request (PR) has been reviewed and merged. 

In addition, each item will be linked to the respective PR for easy reference. This would allow anyone interested to follow the process, review the changes, or participate in the discussion.

Here is the recent plan or progress of adding Cloudberry Database documentation. Note that this list only includes the recently planned docs. Docs that are not present in the list will be added to the list over time.

- Product Introduction
  - [x] Feature Overview. PR: https://github.com/cloudberrydb/cloudberrydb-site/pull/13 (cbdb-overview.md)
  - [x] Architecture. PR: https://github.com/cloudberrydb/cloudberrydb-site/pull/13 (cbdb-architecture.md)
  - [x] User Scenarios. PR: https://github.com/cloudberrydb/cloudberrydb-site/pull/13 (cbdb-scenarios.md)
  - [x] Comparison with Greenplum. PR: https://github.com/cloudberrydb/cloudberrydb-site/pull/11
 
- Deployment Guides
  - [x] On-Premises Deployment Architecture. PR: https://github.com/cloudberrydb/cloudberrydb-site/pull/15 (cbdb-op-deploy-arch.md)
  - [x] Recommended Hardware and Software Configurations. PR: https://github.com/cloudberrydb/cloudberrydb-site/pull/15 (cbdb-op-software-hardware.md)
  - [x] On-Premises Deployment Guide. PR: https://github.com/cloudberrydb/cloudberrydb-site/pull/15 (cbdb-op-deploy-guide.md) (Reverted)
  - [ ] Containerized Deployment Guide.
  - [ ] Cloudberry Quick Start Guide.

For contributors looking to assist with this process:

- Please reference this issue in any PRs related to documentation updates. 
- Feel free to comment on this issue if you'd like to take up a task, have a suggestion, or need further clarification.

We welcome all forms of contributions (refer to [Cloudberry Database Documentation Contribution Guide
](https://github.com/cloudberrydb/cloudberrydb-site/blob/main/src/pages/community/docs-contributing-guide.md)) and thank you for your interest in improving the Cloudberry Database documentation!

**Comment by tuhaihe** [comment]
Luckily, we should already complete all the tasks. So close this issue with done.
